GET http://localhost:8080/paw-2023b-12/institutions HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NGNmMjUxNy00NjgzLTQwMTYtYjQ0My02ZDM4ZDg1OTM5YjMiLCJpc3MiOiJwYXctMjAyM2ItMTIiLCJleHAiOjE3MDQ4MzA2NTAsInRva2VuVHlwZSI6ImFjY2VzcyIsImlhdCI6MTcwNDgzMDA1MCwianRpIjoiNDJlOTJjMDUtMzk5ZS00ODI0LWJkYjEtYTIyNGZjZTY0YzBlIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfU1RVREVOVCJdLCJlbWFpbCI6Im1hcmVuZ290b21hc0BnbWFpbC5jb20ifQ.90nnjnf3QJxsiR-MqKdPRspCWtO3s2o6ROVFrRO6nic
Content-Type: application/json